config/routes.rb
Rails.application.routes.draw do
  resources :sectors
  resources :industries
  resources :appointments
  resources :physicians
  resources :patients
  get 'welcome/index'
  root 'welcome#index'
end

app/models/sector.rb
class Sector < ApplicationRecord
    has_and_belongs_to_many :industries
end

app/controllers/sectors_controller.rb
class SectorsController < ApplicationController
  before_action :set_sector, only: %i[ show edit update destroy ]

  # GET /sectors or /sectors.json
  def index
    @sectors = Sector.all
  end

  # GET /sectors/1 or /sectors/1.json
  def show
  end

  # GET /sectors/new
  def new
    @sector = Sector.new
  end

  # GET /sectors/1/edit
  def edit
  end

  # POST /sectors or /sectors.json
  def create
    @sector = Sector.new(sector_params)

    respond_to do |format|
      if @sector.save
        format.html { redirect_to sector_url(@sector), notice: "Sector was successfully created." }
        format.json { render :show, status: :created, location: @sector }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @sector.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sectors/1 or /sectors/1.json
  def update
    respond_to do |format|
      if @sector.update(sector_params)
        format.html { redirect_to sector_url(@sector), notice: "Sector was successfully updated." }
        format.json { render :show, status: :ok, location: @sector }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @sector.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sectors/1 or /sectors/1.json
  def destroy
    @sector.destroy

    respond_to do |format|
      format.html { redirect_to sectors_url, notice: "Sector was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sector
      @sector = Sector.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def sector_params
      params.require(:sector).permit(:name)
    end
end

app/helpers/sectors_helper.rb
module SectorsHelper
end

app/views/sectors/_form.html.erb
<%= form_with(model: sector, local: true) do |form| %>
  <% if sector.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(sector.errors.count, "error") %> prohibited this sector from being saved:</h2>

      <ul>
        <% sector.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/sectors/edit.html.erb
<h1>Editing Sector</h1>

<%= render 'form', sector: @sector %>

<%= link_to 'Show', @sector %> |
<%= link_to 'Back', sectors_path %>

app/views/sectors/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Sectors</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @sectors.each do |sector| %>
      <tr>
        <td><%= sector.name %></td>
        <td><%= link_to 'Show', sector %></td>
        <td><%= link_to 'Edit', edit_sector_path(sector) %></td>
        <td><%= link_to 'Destroy', sector, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Sector', new_sector_path %>

app/views/sectors/new.html.erb
<h1>New Sector</h1>

<%= render 'form', sector: @sector %>

<%= link_to 'Back', sectors_path %>

app/views/sectors/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @sector.name %>
</p>

<%= link_to 'Edit', edit_sector_path(@sector) %> |
<%= link_to 'Back', sectors_path %>