config/routes.rb
Rails.application.routes.draw do
  resources :sectors
  resources :industries
  resources :appointments
  resources :physicians
  resources :patients
  get 'welcome/index'
  root 'welcome#index'
end

app/models/physician.rb
class Physician < ApplicationRecord
    has_many :appointments, dependent: :destroy
    has_many :patients, through: :appointments

    before_save { self.email = email.downcase }
    before_save { self.unique_id = SecureRandom.uuid }
    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

    validates :name, presence: true, length: { in: 3..25, message: "Name length should be between 3 and 25 characters" }
    validates :email, presence: true, 
                        uniqueness: { case_sensitive: false }, 
                        length: { maximum: 105 },
                        format: { with: VALID_EMAIL_REGEX}
    validates :unique_id, uniqueness: true

end

app/controllers/physicians_controller.rb
class PhysiciansController < ApplicationController
  before_action :set_physician, only: %i[ show edit update destroy ]

  # GET /physicians or /physicians.json
  def index
    @physicians = Physician.all
  end

  # GET /physicians/1 or /physicians/1.json
  def show
  end

  # GET /physicians/new
  def new
    @physician = Physician.new
  end

  # GET /physicians/1/edit
  def edit
  end

  # POST /physicians or /physicians.json
  def create
    @physician = Physician.new(physician_params)

    respond_to do |format|
      if @physician.save
        format.html { redirect_to physician_url(@physician), notice: "Physician was successfully created." }
        format.json { render :show, status: :created, location: @physician }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @physician.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /physicians/1 or /physicians/1.json
  def update
    respond_to do |format|
      if @physician.update(physician_params)
        format.html { redirect_to physician_url(@physician), notice: "Physician was successfully updated." }
        format.json { render :show, status: :ok, location: @physician }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @physician.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /physicians/1 or /physicians/1.json
  def destroy
    @physician.destroy

    respond_to do |format|
      format.html { redirect_to physicians_url, notice: "Physician was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_physician
      @physician = Physician.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def physician_params
      params.require(:physician).permit(:name, :email, :unique_id)
    end
end

app/helpers/physicians_helper.rb
module PhysiciansHelper
end

app/views/physicians/_form.html.erb
<%= form_with(model: physician, local: true) do |form| %>
  <% if physician.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(physician.errors.count, "error") %> prohibited this physician from being saved:</h2>

      <ul>
        <% physician.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/physicians/edit.html.erb
<h1>Editing Physician</h1>

<%= render 'form', physician: @physician %>

<%= link_to 'Show', @physician %> |
<%= link_to 'Back', physicians_path %>

app/views/physicians/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Physicians</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Unique</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @physicians.each do |physician| %>
      <tr>
        <td><%= physician.name %></td>
        <td><%= physician.email %></td>
        <td><%= physician.unique_id %></td>
        <td><%= link_to 'Show', physician %></td>
        <td><%= link_to 'Edit', edit_physician_path(physician) %></td>
        <td><%= link_to 'Destroy', physician, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Physician', new_physician_path %>

app/views/physicians/new.html.erb
<h1>New Physician</h1>

<%= render 'form', physician: @physician %>

<%= link_to 'Back', physicians_path %>

app/views/physicians/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @physician.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @physician.email %>
</p>

<p>
  <strong>Unique:</strong>
  <%= @physician.unique_id %>
</p>

<%= link_to 'Edit', edit_physician_path(@physician) %> |
<%= link_to 'Back', physicians_path %>