config/routes.rb
Rails.application.routes.draw do
  resources :sectors
  resources :industries
  resources :appointments
  resources :physicians
  resources :patients
  get 'welcome/index'
  root 'welcome#index'
end

app/models/industry.rb
class Industry < ApplicationRecord
    has_and_belongs_to_many :sectors 

    before_save { self.email = email.downcase }
    before_save { self.registration_number = SecureRandom.uuid }

    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

    validates :name, presence: true, length: { in: 3..100, message: "Name length should be between 3 and 100 characters" }
    validates :email, presence: true, 
                        uniqueness: { case_sensitive: false }, 
                        length: { maximum: 105 },
                        format: { with: VALID_EMAIL_REGEX}
    validates :registration_number, uniqueness: true
end

app/controllers/industries_controller.rb
class IndustriesController < ApplicationController
  before_action :set_industry, only: %i[ show edit update destroy ]

  # GET /industries or /industries.json
  def index
    @industries = Industry.all
  end

  # GET /industries/1 or /industries/1.json
  def show
  end

  # GET /industries/new
  def new
    @industry = Industry.new
  end

  # GET /industries/1/edit
  def edit
  end

  # POST /industries or /industries.json
  def create
    @industry = Industry.new(industry_params)

    respond_to do |format|
      if @industry.save
        format.html { redirect_to industry_url(@industry), notice: "Industry was successfully created." }
        format.json { render :show, status: :created, location: @industry }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @industry.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /industries/1 or /industries/1.json
  def update
    respond_to do |format|
      if @industry.update(industry_params)
        format.html { redirect_to industry_url(@industry), notice: "Industry was successfully updated." }
        format.json { render :show, status: :ok, location: @industry }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @industry.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /industries/1 or /industries/1.json
  def destroy
    @industry.destroy

    respond_to do |format|
      format.html { redirect_to industries_url, notice: "Industry was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_industry
      @industry = Industry.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def industry_params
      params.require(:industry).permit(:name, :email, :registration_number)
    end
end

app/helpers/industries_helper.rb
module IndustriesHelper
end

app/views/industries/_form.html.erb
<%= form_with(model: industry, local: true) do |form| %>
  <% if industry.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(industry.errors.count, "error") %> prohibited this industry from being saved:</h2>

      <ul>
        <% industry.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/industries/edit.html.erb
<h1>Editing Industry</h1>

<%= render 'form', industry: @industry %>

<%= link_to 'Show', @industry %> |
<%= link_to 'Back', industries_path %>

app/views/industries/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Industries</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Registration number</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @industries.each do |industry| %>
      <tr>
        <td><%= industry.name %></td>
        <td><%= industry.email %></td>
        <td><%= industry.registration_number %></td>
        <td><%= link_to 'Show', industry %></td>
        <td><%= link_to 'Edit', edit_industry_path(industry) %></td>
        <td><%= link_to 'Destroy', industry, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Industry', new_industry_path %>

app/views/industries/new.html.erb
<h1>New Industry</h1>

<%= render 'form', industry: @industry %>

<%= link_to 'Back', industries_path %>

app/views/industries/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @industry.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @industry.email %>
</p>

<p>
  <strong>Registration number:</strong>
  <%= @industry.registration_number %>
</p>

<%= link_to 'Edit', edit_industry_path(@industry) %> |
<%= link_to 'Back', industries_path %>